data_dir: data
exp_dir: exp
model_type_global: ecapa_ssl # ecapa or xvector or ecapa_ssl

anon_data_suffix: _mcadams # added to transform data/libri_dev/ to data/libri_dev_mcadams/

results_summary_path: !ref <exp_dir>/results_summary/eval_anon<anon_data_suffix>/results_anon.txt

train_data_name: !ref train-clean-360<anon_data_suffix>

datasets:
  - name: libri_dev
    data: libri_dev
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]
  - name: libri_test
    data: libri_test
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]

eval_steps:
  privacy:
    - asv

privacy:
  asv:
    model_type: !ref <model_type_global>
    dataset_name: [libri_dev, libri_test]
    training:
      model_type: !ref <model_type_global>
      model_dir: !ref <exp_dir>/asv_anon<anon_data_suffix> # path to existing ASV model or output for trained ASV model
      train_data_dir: !ref <data_dir>/<train_data_name> # path to original or anonymized training data for ASV
      train_config: !ref evaluation/privacy/asv/asv_train/hparams/train_<model_type_global>_tdnn_small.yaml
      infer_config: !ref evaluation/privacy/asv/asv_train/hparams/ecapa/<model_type_global>_hyperparams.yaml
      finetuning: True # true (ft) or false (scratch)
      pretrained_model: exp/asv_ssl/embedding_model.ckpt # path to pretrained model, only used for finetuning
      pretrained_wavlm_model: exp/asv_ssl/WavLM-Large.pt # path to pretrained model, only used for ecapa_ssl training, should be a .pth path
      lr: 0.01
      epochs: 2
      batch_size: 8
      num_workers: 10 #increse this can speed up the training process
      num_utt: ALL # ALL or specific number, number of utterances per speaker
      num_utt_per_spk: 50 # ALL or specific number, number of utterances per speaker
      utt_selection: spk-diverse-sess # select utterances per speaker and session (spk-sess), per speaker and randomly across all sessions (spk-random), per speaker and balanced across sessions (spk-diverse-sess)
      num_spk: ALL # ALL or specific number, number of speakers
      retrain: true # retrain in any case (true) or skip training if model exists (false)

    evaluation:
      model_dir: !ref <exp_dir>/asv_anon<anon_data_suffix> # path to existing ASV model or output for trained ASV model
      results_dir: !ref <exp_dir>/asv_anon<anon_data_suffix> # path to existing ASV model or output for trained ASV model
      distance: cosine # cosine or plda
      plda: # ignored if distance is not plda
        model_dir: null # path to trained PLDA or output of PLDA training
        train_data_dir: null # path to PLDA training data
        anon: null # trained on anonymized (true) or original (false) data
