data_dir: data
results_dir: data # output example ./data/mls_german_ssl

pipeline: ssl
anon_suffix: !ref _<pipeline>

datasets:
  - name: train_chinese
    data: train_chinese
  - name: train_japanese
    data: train_japanese
  - name: train_english
    data: train_english
  - name: train_german
    data: train_german
  - name: train_spanish
    data: train_spanish
  - name: train_french
    data: train_french


modules:
  anon_suffix: !ref <anon_suffix>
  anon_level_random_per_utt:      [train_chinese, train_japanese, train_english, train_german, train_spanish, train_french] # Overwrite anon_level_constant because above
  anon_level_constant:            [train_chinese, train_japanese, train_english, train_german, train_spanish, train_french]
  #target_constant_spkid: "6081" # For anon_level_constant, must be one of the training data (libriTTS)
  device: "cuda"
  batch_size: 8 # works with GPU < 12Gib
