data_dir: data
results_dir: wav # output example ./data/IEMOCAP_asrbn-vq/wav

pipeline: asrbn
anon_suffix: !ref _<pipeline>_<modules[model_tag_version]>

datasets:
  #- name: mls_german_test
  #  data: mls_german_test
  #  enrolls: [_enrolls]
  #  trials: [_trials_f, _trials_m]
  #- name: mls_italian_test
  #  data: mls_italian_test
  #  enrolls: [_enrolls]
  #  trials: [_trials_f, _trials_m]
  #- name: mls_french_test
  #  data: mls_french_test
  #  enrolls: [_enrolls]
  #  trials: [_trials_f, _trials_m]
  #- name: mls_polish_test
  #  data: mls_polish_test
  #  enrolls: [_enrolls]
  #  trials: [_trials_f, _trials_m]
  #- name: mls_portuguese_test
  #  data: mls_portuguese_test
  #  enrolls: [_enrolls]
  #  trials: [_trials_f, _trials_m]
  #- name: mls_spanish_test
  #    enrolls: [_enrolls]
  #  trials: [_trials_f, _trials_m]
  - name: mls_dutch_test
    data: mls_dutch_test
    enrolls: [_enrolls]
    trials: [_trials_f, _trials_m]

modules:
  anon_suffix: !ref <anon_suffix>
  anon_level_random_per_utt:      [mls_german_test, mls_italian_test, mls_french_test, mls_polish_test, mls_portuguese_test, mls_spanish_test, mls_dutch_test] # Overwrite anon_level_constant because above
  anon_level_constant:            [mls_german_test, mls_italian_test, mls_french_test, mls_polish_test, mls_portuguese_test, mls_spanish_test, mls_dutch_test]
  target_constant_spkid: "6081" # For anon_level_constant, must be one of the training data (libriTTS)
  ### Many models can be found here: https://github.com/deep-privacy/SA-toolkit/releases
  ### Online demo here: https://huggingface.co/spaces/Champion/SA-toolkit
  # model_tag_version: "hifigan_bn_tdnnf_600h_aug_v1" # NO VQ
  # model_tag_version: "hifigan_bn_tdnnf_wav2vec2_100h_aug_v1" # NO VQ
  # model_tag_version: "hifigan_bn_tdnnf_600h_vq_48_v1"   # This is B6
  model_tag_version: "hifigan_bn_tdnnf_wav2vec2_vq_48_v1" # This is B5
  device: "cuda"
  batch_size: 8 # works with GPU < 12Gib
